import type { ModuleContent, CheckRequest, KpOutput } from '../schemas/index.js';
import type { CheckResult, SanCheckResult, Outcome } from '../rules/index.js';

// ---------------------------------------------------------------------------
// Runtime session state -- the in-memory mirror of what the DB will hold.
// Every field has a direct counterpart in supabase/migrations/0001_init.sql.
// ---------------------------------------------------------------------------

export interface InvestigatorSnapshot {
  name: string;
  era: string;
  occupation: string | null;
  age: number | null;
  stats: {
    str: number; con: number; siz: number; dex: number;
    app: number; int: number; pow: number; edu: number;
  };
  hp_max: number;
  mp_max: number;
  san_max: number;
  san_start: number;
  luck_start: number;
  mov: number;
  damage_bonus: string;
  build: number;
  skills: Record<string, { base: number; value: number }>;
  inventory: InventoryItem[];
  background: Record<string, unknown>;
}

export interface InventoryItem {
  item: string;
  qty: number;
  notes?: string;
}

export interface InvestigatorRuntimeState {
  hp_current: number;
  mp_current: number;
  san_current: number;
  luck: number;
  skills: Record<string, { base: number; value: number; used_this_session: boolean }>;
  inventory: InventoryItem[];
  conditions: string[];        // 'bleeding', 'injured', 'temp_insanity', 'indefinite_insanity', ...
  phobias_manias: string[];
}

export interface SessionClueState {
  clue_key: string;
  discovered: boolean;
  discovered_at?: string;
  discovery_context?: string;
  player_notes?: string;
}

export interface SessionNpcState {
  npc_key: string;
  disposition: 'hostile' | 'wary' | 'neutral' | 'friendly' | 'ally';
  alive: boolean;
  hp_current: number | null;
  san_modifier: number;
  notes: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Turn log.  Mirrors `turns` + embeds check resolution produced THIS turn.
// ---------------------------------------------------------------------------

export type Actor = 'player' | 'kp' | 'system';

export interface TurnRecord {
  id: string;                   // uuid, generated by engine (so checks/events can reference)
  index: number;
  actor: Actor;
  player_input?: string;
  kp_output?: KpOutput;
  visible_narration?: string;
  check_resolution?: CheckResolution;
  created_at: string;
}

export interface CheckResolution {
  request: CheckRequest;
  kind: 'skill_like' | 'san';
  skill_result?: CheckResult;
  san_result?: SanCheckResult;
  /** Short human-readable summary, e.g. "侦查 60 (regular): 掷出 35 -> regular_success". */
  summary: string;
  /** Flag propagated so the KP can know what happened. */
  outcome: Outcome | 'san_passed' | 'san_failed';
}

// ---------------------------------------------------------------------------
// Events -- append-only log of structured changes.  Map 1:1 to session_events.
// ---------------------------------------------------------------------------

export type SessionEvent =
  | { kind: 'clock_advance'; minutes: number; reason?: string; at: string }
  | { kind: 'hp_change'; delta: number; new_value: number; reason?: string; at: string }
  | { kind: 'mp_change'; delta: number; new_value: number; reason?: string; at: string }
  | { kind: 'san_change'; delta: number; new_value: number; reason?: string; at: string }
  | { kind: 'luck_change'; delta: number; new_value: number; reason?: string; at: string }
  | { kind: 'damage_roll'; expression: string; rolled: number; armor: number; applied: number; at: string }
  | { kind: 'san_check'; loss: string; d100: number; passed: boolean; lost: number; source: string; at: string }
  | { kind: 'inventory_add'; item: string; qty: number; notes?: string; at: string }
  | { kind: 'inventory_remove'; item: string; qty: number; at: string }
  | { kind: 'clue_found'; clue_key: string; context?: string; at: string }
  | { kind: 'npc_disposition'; npc_key: string; disposition: SessionNpcState['disposition']; at: string }
  | { kind: 'npc_dead'; npc_key: string; cause?: string; at: string }
  | { kind: 'scene_change'; from: string; to: string; at: string }
  | { kind: 'flag_set'; key: string; value: string | number | boolean | null; at: string }
  | { kind: 'check_resolved'; request: CheckRequest; summary: string; at: string }
  | { kind: 'temp_insanity_threshold'; loss: number; at: string }
  | { kind: 'character_dead'; at: string }
  | { kind: 'character_insane'; permanent: boolean; at: string };

// ---------------------------------------------------------------------------
// Top-level session state.
// ---------------------------------------------------------------------------

export type SessionStatus = 'active' | 'completed' | 'abandoned' | 'failed';

export interface SessionState {
  session_id: string;
  owner_id: string;
  investigator_id: string;
  module_id: string;

  investigator: {
    base: InvestigatorSnapshot;
    current: InvestigatorRuntimeState;
  };
  module: ModuleContent;

  current_scene_id: string;
  game_clock: { elapsed_minutes: number };

  turns: TurnRecord[];
  events: SessionEvent[];
  clues: Record<string, SessionClueState>;
  npcs: Record<string, SessionNpcState>;
  flags: Record<string, string | number | boolean | null>;

  /** If set, the next player action resolves this check before the KP goes again. */
  pending_check: CheckRequest | null;

  status: SessionStatus;
  ending?: string;

  started_at: string;
  updated_at: string;
}
