-- =====================================================================
-- 0004_commit_turn.sql
-- Atomic turn commit: one RPC takes a jsonb payload and performs every
-- write for a turn in a single transaction (Postgres functions run inside
-- an implicit transaction, so a raise inside aborts all writes).
--
-- Payload shape (all fields required unless noted):
--   {
--     "session_id": uuid,
--     "new_turns":      [{ id, turn_index, actor, player_input, kp_output,
--                          visible_narration, created_at }, ...],
--     "new_checks":     [{ turn_id, kind, skill_or_stat, target, difficulty,
--                          bonus_dice, penalty_dice, roll_raw, roll_result,
--                          outcome, pushed }, ...],
--     "new_events":     [{ kind, payload, created_at }, ...],
--     "clue_upserts":   [{ clue_key, discovered, discovered_at,
--                          discovery_context, player_notes }, ...],
--     "npc_upserts":    [{ npc_key, disposition, alive, hp_current,
--                          san_modifier, notes }, ...],
--     "investigator_current_state": jsonb,
--     "session_patch": {
--        current_scene_id, game_clock, status, ending,
--        pending_check, flags, updated_at
--     }
--   }
-- =====================================================================

create or replace function public.commit_turn(payload jsonb)
returns void
language plpgsql
security invoker
as $$
declare
  s_id uuid := (payload->>'session_id')::uuid;
  patch jsonb := payload->'session_patch';
begin
  -- 1. insert new turns
  insert into public.turns
    (id, session_id, turn_index, actor, player_input, kp_output,
     visible_narration, created_at)
  select
    (t->>'id')::uuid,
    s_id,
    (t->>'turn_index')::int,
    t->>'actor',
    t->>'player_input',
    case when t->'kp_output' = 'null'::jsonb then null else t->'kp_output' end,
    t->>'visible_narration',
    coalesce((t->>'created_at')::timestamptz, now())
  from jsonb_array_elements(coalesce(payload->'new_turns', '[]'::jsonb)) as t;

  -- 2. insert new checks (turn_id is already a uuid generated by the engine)
  insert into public.checks
    (session_id, turn_id, kind, skill_or_stat, target, difficulty,
     bonus_dice, penalty_dice, roll_raw, roll_result, outcome, pushed)
  select
    s_id,
    (c->>'turn_id')::uuid,
    c->>'kind',
    c->>'skill_or_stat',
    nullif(c->>'target','')::int,
    nullif(c->>'difficulty',''),
    coalesce((c->>'bonus_dice')::int, 0),
    coalesce((c->>'penalty_dice')::int, 0),
    c->'roll_raw',
    (c->>'roll_result')::int,
    c->>'outcome',
    coalesce((c->>'pushed')::bool, false)
  from jsonb_array_elements(coalesce(payload->'new_checks', '[]'::jsonb)) as c;

  -- 3. insert session_events
  insert into public.session_events
    (session_id, turn_id, kind, payload, created_at)
  select
    s_id,
    null::uuid,
    e->>'kind',
    coalesce(e->'payload', '{}'::jsonb),
    coalesce((e->>'created_at')::timestamptz, now())
  from jsonb_array_elements(coalesce(payload->'new_events', '[]'::jsonb)) as e;

  -- 4. upsert session_clues
  insert into public.session_clues
    (session_id, clue_key, discovered, discovered_at, discovery_context, player_notes)
  select
    s_id,
    c->>'clue_key',
    coalesce((c->>'discovered')::bool, false),
    nullif(c->>'discovered_at','')::timestamptz,
    c->>'discovery_context',
    c->>'player_notes'
  from jsonb_array_elements(coalesce(payload->'clue_upserts', '[]'::jsonb)) as c
  on conflict (session_id, clue_key) do update
    set discovered        = excluded.discovered,
        discovered_at     = excluded.discovered_at,
        discovery_context = excluded.discovery_context,
        player_notes      = excluded.player_notes;

  -- 5. upsert session_npcs
  insert into public.session_npcs
    (session_id, npc_key, disposition, alive, hp_current, san_modifier, notes)
  select
    s_id,
    n->>'npc_key',
    n->>'disposition',
    coalesce((n->>'alive')::bool, true),
    nullif(n->>'hp_current','')::int,
    coalesce((n->>'san_modifier')::int, 0),
    coalesce(n->'notes', '{}'::jsonb)
  from jsonb_array_elements(coalesce(payload->'npc_upserts', '[]'::jsonb)) as n
  on conflict (session_id, npc_key) do update
    set disposition  = excluded.disposition,
        alive        = excluded.alive,
        hp_current   = excluded.hp_current,
        san_modifier = excluded.san_modifier,
        notes        = excluded.notes;

  -- 6. replace session_investigator_state.current_state
  update public.session_investigator_state
     set current_state = payload->'investigator_current_state',
         updated_at    = now()
   where session_id = s_id;

  -- 7. patch sessions
  update public.sessions
     set current_scene_id = patch->>'current_scene_id',
         game_clock       = patch->'game_clock',
         status           = patch->>'status',
         ending           = nullif(patch->>'ending',''),
         pending_check    = case when patch->'pending_check' = 'null'::jsonb
                                   or patch->'pending_check' is null
                                 then null else patch->'pending_check' end,
         flags            = coalesce(patch->'flags', '{}'::jsonb),
         updated_at       = coalesce((patch->>'updated_at')::timestamptz, now()),
         ended_at         = case when (patch->>'status') <> 'active' then now() else ended_at end
   where id = s_id;
end;
$$;

-- Allow authenticated users to call the RPC.  RLS on underlying tables still
-- applies because the function runs with security invoker.
grant execute on function public.commit_turn(jsonb) to authenticated, service_role;
